# Generated by Django 6.0.3 on 2026-04-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatchs_service_cotizador', '0002_alter_detallecotizacion_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
