# Generated by Django 6.0.3 on 2026-04-11 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatchs_service_cotizador', '0004_remove_detallecotizacion_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='numero_cotizacion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yatchs_service_cotizador.producto'),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yatchs_service_cotizador.servicio'),
        ),
    ]
