# Generated by Django 6.0.3 on 2026-04-12 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatchs_service_cotizador', '0005_cotizacion_numero_cotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yatchs_service_cotizador.cliente'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
