# Generated by Django 6.0.3 on 2026-04-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatchs_service_cotizador', '0008_alter_cotizacion_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecotizacion',
            name='codigo',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='nombre',
            field=models.CharField(default='Jabon', max_length=30),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
