# Generated by Django 6.0.3 on 2026-04-12 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yatchs_service_cotizador', '0009_detallecotizacion_codigo_detallecotizacion_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='precio_unitario',
        ),
    ]
