# Generated by Django 6.0.3 on 2026-04-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatchs_service_cotizador', '0011_rename_fecha_cotizacion_fecha_caducidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_creacion',
            field=models.DateField(),
        ),
    ]
