# Generated by Django 6.0.3 on 2026-04-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatchs_service_cotizador', '0013_remove_cotizacion_numero_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='numero_cotizacion',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
