# Generated by Django 6.0.3 on 2026-04-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatchs_service_cotizador', '0014_cotizacion_numero_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_caducidad',
            field=models.DateField(),
        ),
    ]
