# Generated by Django 6.0.3 on 2026-04-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatchs_service_cotizador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecotizacion',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
