# Generated by Django 6.0.3 on 2026-04-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yatchs_service_cotizador', '0003_cotizacion_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='iva',
        ),
    ]
