# Generated by Django 6.0.3 on 2026-04-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatchs_service_cotizador', '0007_alter_cotizacion_cliente_alter_cotizacion_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='numero_cotizacion',
            field=models.IntegerField(),
        ),
    ]
