# Generated by Django 6.0.3 on 2026-04-23 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatchs_service_cotizador', '0010_remove_detallecotizacion_codigo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='fecha',
            new_name='fecha_caducidad',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 4, 23, 1, 42, 47, 274067, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='cotizaciones_pdfs/'),
        ),
    ]
