# Generated by Django 6.0.3 on 2026-04-23 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yatchs_service_cotizador', '0012_alter_cotizacion_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='numero_cotizacion',
        ),
    ]
